export default {
    typesArrayKey: "types",
    statsArrayKey: "stats",
    thingsArrayKey: "things",
    timePeriodsArrayKey: "timePeriods",
    observationsArrayKey: "observations",
    createdObservationsArrayKey: "createdObservations",
    invalidObservationsArrayKey: "invalidObservations",
    subscriptionsArrayKey: "subscriptions",
    invalidUserKey: "invalidUser",
    invalidMeasurementKey: "invalidMeasurement",
    invalidEventKey: "invalidEvent",
    invalidThingKey: "invalidThing",
    invalidDateRangeKey: "invalidDateRange",
    invalidSubscriptionKey: "invalidSubscription",
    startDateKey: "startDate",
    endDateKey: "endDate",
    invalidTimePeriod: "invalidTimePeriod",
    invalidCoordinateParamsKey: "invalidCoordinateParams",
    longitudeKey: "longitude",
    latitudeKey: "latitude",
    addressKey: "addressKey",
    mandatoryQueryParamKey: "mandatoryQueryParam",
    invalidQueryParamKey: "invalidQueryParam",
    chatIdKey: "chatId",
};