export default {
    typesArrayKey: "types",
    statsArrayKey: "stats",
    thingsArrayKey: "things",
    observationsArrayKey: "observations",
    createdObservationsArrayKey: "createdObservations",
    invalidObservationsArrayKey: "invalidObservations",
    invalidUserKey: "invalidUser",
    invalidMeasurementKey: "invalidMeasurement",
    invalidEventKey: "invalidEvent",
    invalidThingKey: "invalidThing",
    invalidDateRangeKey: "invalidDateRange",
    startDateKey: "startDate",
    endDateKey: "endDate",
    invalidLastTimePeriodKey: "invalidTimePeriod",
    invalidRegionParamsKey: "invalidRegionParams",
    longitudeKey: "longitude",
    latitudeKey: "latitude",
    addressKey: "addressKey"
};